apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pediacare-ingress
  namespace: pediacare
spec:
  rules:
    - host: api.pediacare.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 3000
    - host: website.pediacare.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: website
                port:
                  number: 3001
    - host: admin.pediacare.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: admin
                port:
                  number: 3002
